// Code generated by goctl. DO NOT EDIT.
package types

type GroupCreateRequest struct {
	UserId     uint   `header:"UserId"`   //创建人id
	Mode       uint8  `json:"mode"`       //模式： 1直接创建 2选人创建
	Name       string `json:"name"`       //群名称
	IsSearch   bool   `json:"isSearch"`   //是否允许搜索
	Size       uint   `json:"size"`       //群大小
	UserIdList []uint `json:"userIdList"` //用户列表
}

type GroupCreateResponse struct {
	GroupId uint `json:"groupId"`
}

type GroupInfoRequest struct {
	UserId  uint `header:"UserId"`
	GroupId uint `json:"groupId"`
}

type GroupInfoResponse struct {
	GroupId     uint       `json:"groupId"`
	Title       string     `json:"title"`
	Abstract    string     `json:"abstract"`
	Avatar      string     `json:"avatar"`
	MemberCount int        `json:"memberCount"`
	OnlineCount int        `json:"onlineCount"`
	Creator     UserInfo   `json:"creator"`
	AdminList   []UserInfo `json:"adminList"`
}

type UserInfo struct {
	UserId   uint   `json:"userId"`
	UserName string `json:"userName"`
	Avatar   string `json:"avatar"`
}
