// Code generated by goctl. DO NOT EDIT.
package types

type GroupCreateRequest struct {
	UserId     uint   `header:"UserId"`   //创建人id
	Mode       uint8  `json:"mode"`       //模式： 1直接创建 2选人创建
	Name       string `json:"name"`       //群名称
	IsSearch   bool   `json:"isSearch"`   //是否允许搜索
	Size       uint   `json:"size"`       //群大小
	UserIdList []uint `json:"userIdList"` //用户列表
}

type GroupCreateResponse struct {
	GroupId uint `json:"groupId"`
}
