// Code generated by goctl. DO NOT EDIT.
package types

type ChatHistoryRequest struct {
	UserId uint `header:"UserId"`
	Page   uint `form:"page"`
	Limit  uint `form:"limit"`
}

type ChatHistoryResponse struct {
	MsgId     uint   `json:"msgId"`
	UserId    uint   `json:"userId"`
	Avatar    string `json:"avatar"`
	Nickname  string `json:"nickname"`
	CreatedAt string `json:"createdAt"`
}

type ChatSessionDisplayRequest struct {
	UserId uint `header:"UserId"`
	Page   uint `form:"page"`
	Limit  uint `form:"limit"`
	Key    int  `form:"key"`
}

type ChatSessionDisplay struct {
	UserId     uint   `json:"userId"`
	Avatar     string `json:"avatar"`
	Nickname   string `json:"nickname"`
	CreatedAt  string `json:"created_at"`
	MsgPreview string `json:"msgPreview"`
}
type ChatSessionDisplayResponse struct {
	List  []ChatSessionDisplay `json:"list"`
	Count int                 `json:"count"`
}
