apiVersion: fim/v1
kind: Deployment
metadata:
  name: mysql_deployment
spec:
  replicas: 1 //定义运行该服务的副本数量， 1表示只有一个pod在运行该服务
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "wpywatsendw0517"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql_data
          mountPath: /var/lib/mysql
  volumes:
  - name: mysql_data
    persistentVolumeClaim:
      claimName: mysql_pvc

