// Code generated by goctl. DO NOT EDIT.
package types

type AuthenticationResponse struct {
	Code int    `json:"code"`
	Data string `json:"data"`
	Msg  string `json:"msg"`
}

type LoginInfo struct {
	Token string `json:"token"`
}

type LoginRequest struct {
	UserName string `json:"userName"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Code int       `json:"code"`
	Data LoginInfo `json:"data"`
	Msg  string    `json:"msg"`
}

type Response struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type ThirdPartyLoginInfo struct {
	Name string `json:"name"`
	Icon string `json:"icon"`
	Url  string `json:"url"` //跳转地址
}

type ThirdPartyLoginInfoResponse struct {
	Code int                   `json:"code"`
	Data []ThirdPartyLoginInfo `json:"data"`
	Msg  string                `json:"msg"`
}

type ThirdPartyLoginRequest struct {
	ThirdParty string `json:"thirdParty"`
	Code       string `json:"code"`
	Flag       string `json:"flag"`
}
