// Code generated by goctl. DO NOT EDIT.
// Source: group_rpc.proto

package server

import (
	"context"

	"fim/fim_group/group_rpc/internal/logic"
	"fim/fim_group/group_rpc/internal/svc"
	"fim/fim_group/group_rpc/types/group_rpc"
)

type GroupServer struct {
	svcCtx *svc.ServiceContext
	group_rpc.UnimplementedGroupServer
}

func NewGroupServer(svcCtx *svc.ServiceContext) *GroupServer {
	return &GroupServer{
		svcCtx: svcCtx,
	}
}

func (s *GroupServer) GroupMemberInfo(ctx context.Context, in *group_rpc.MemberInfoRequest) (*group_rpc.MemberInfoResponse, error) {
	l := logic.NewGroupMemberInfoLogic(ctx, s.svcCtx)
	return l.GroupMemberInfo(in)
}
