// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"fim/fim_chat/chat_api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/chat/chat_delete",
				Handler: ChatDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/chat/chat_history",
				Handler: ChatHistoryHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/chat/chat_pin",
				Handler: ChatPinHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/chat/chat_session_display",
				Handler: ChatSessionDisplayHandler(serverCtx),
			},
		},
	)
}
