// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.27.0
// source: group_rpc.proto

package group_rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MemberInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Member uint32 `protobuf:"varint,1,opt,name=member,proto3" json:"member,omitempty"`
	Group  uint32 `protobuf:"varint,2,opt,name=group,proto3" json:"group,omitempty"`
}

func (x *MemberInfoRequest) Reset() {
	*x = MemberInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_group_rpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemberInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberInfoRequest) ProtoMessage() {}

func (x *MemberInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_group_rpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberInfoRequest.ProtoReflect.Descriptor instead.
func (*MemberInfoRequest) Descriptor() ([]byte, []int) {
	return file_group_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *MemberInfoRequest) GetMember() uint32 {
	if x != nil {
		return x.Member
	}
	return 0
}

func (x *MemberInfoRequest) GetGroup() uint32 {
	if x != nil {
		return x.Group
	}
	return 0
}

type MemberInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   int32  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName string `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Avatar   string `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Role     int32  `protobuf:"varint,4,opt,name=role,proto3" json:"role,omitempty"`
}

func (x *MemberInfoResponse) Reset() {
	*x = MemberInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_group_rpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemberInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberInfoResponse) ProtoMessage() {}

func (x *MemberInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_group_rpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberInfoResponse.ProtoReflect.Descriptor instead.
func (*MemberInfoResponse) Descriptor() ([]byte, []int) {
	return file_group_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *MemberInfoResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MemberInfoResponse) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *MemberInfoResponse) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *MemberInfoResponse) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

var File_group_rpc_proto protoreflect.FileDescriptor

var file_group_rpc_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x72, 0x70, 0x63, 0x22, 0x41, 0x0a, 0x11,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x22,
	0x76, 0x0a, 0x12, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b,
	0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61,
	0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x32, 0x57, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x12, 0x4e, 0x0a, 0x0f, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x1c, 0x2e, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x72, 0x70, 0x63, 0x2e,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1d, 0x2e, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x72, 0x70, 0x63, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_group_rpc_proto_rawDescOnce sync.Once
	file_group_rpc_proto_rawDescData = file_group_rpc_proto_rawDesc
)

func file_group_rpc_proto_rawDescGZIP() []byte {
	file_group_rpc_proto_rawDescOnce.Do(func() {
		file_group_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_group_rpc_proto_rawDescData)
	})
	return file_group_rpc_proto_rawDescData
}

var file_group_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_group_rpc_proto_goTypes = []interface{}{
	(*MemberInfoRequest)(nil),  // 0: group_rpc.MemberInfoRequest
	(*MemberInfoResponse)(nil), // 1: group_rpc.MemberInfoResponse
}
var file_group_rpc_proto_depIdxs = []int32{
	0, // 0: group_rpc.group.GroupMemberInfo:input_type -> group_rpc.MemberInfoRequest
	1, // 1: group_rpc.group.GroupMemberInfo:output_type -> group_rpc.MemberInfoResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_group_rpc_proto_init() }
func file_group_rpc_proto_init() {
	if File_group_rpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_group_rpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MemberInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_group_rpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MemberInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_group_rpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_group_rpc_proto_goTypes,
		DependencyIndexes: file_group_rpc_proto_depIdxs,
		MessageInfos:      file_group_rpc_proto_msgTypes,
	}.Build()
	File_group_rpc_proto = out.File
	file_group_rpc_proto_rawDesc = nil
	file_group_rpc_proto_goTypes = nil
	file_group_rpc_proto_depIdxs = nil
}
