apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: ClusterIP    # 默认类型，集群内部使用
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306        # Service 暴露的端口
      targetPort: 3306  # Pod 内部容器的端口
