apiVersion: v1
kind: Service
metadata:
  name: user_api_service
spec:
  type: NodePort
  selector:
    app: fim_user_api
  ports:
    - protocol: TCP
      port: 80        # 服务暴露的端口
      targetPort: 8899  # Pod 内部容器监听的端口
      nodePort: 30087  # 外部访问的端口 (30000-32767 之间)
