// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"fim/fim_user/user_api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/user/friend_info",
				Handler: GetFriendInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/user/friend_list",
				Handler: GetFriendListHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/user/friend_notice_update",
				Handler: FrinedNoticeUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/user/user_conf",
				Handler: GetUserConfHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/user/user_conf_update",
				Handler: UserConfUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/user/user_info",
				Handler: GetUserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/user/user_info_update",
				Handler: UserInfoUpdateHandler(serverCtx),
			},
		},
	)
}
