// Code generated by goctl. DO NOT EDIT.
package types

type ImageShowRequest struct {
	ImageType string `path:"imageType"`
	ImageName string `path:"imageName"`
}

type ImageUploadRequest struct {
}

type ImageUploadResponse struct {
	Url string `json:"url"`
}
