// Code generated by goctl. DO NOT EDIT.
package types

type FileRequest struct {
	UserId uint `header:"UserId"`
}

type FileResponse struct {
	Src string `json:"src"`
}

type ImageShowRequest struct {
	ImageType string `path:"imageType"`
	ImageName string `path:"imageName"`
}

type ImageUploadRequest struct {
}

type ImageUploadResponse struct {
	Url string `json:"url"`
}
