// Code generated by goctl. DO NOT EDIT.
package types

type UserInfoRequest struct {
	UserId uint `header:"UserId"`
}

type UserInfoResponse struct {
	Id       uint   `json:"id"`
	Nickname string `json:"nickname"`
	Role     int8   `json:"role"`
	Abstract string `json:"abstract"`
	Avatar   string `json:"avatar"`
}
